// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
}

type Workflow struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	State            string         `json:"state"`
	PlanJson         sql.NullString `json:"plan_json"`
	ConfigJson       sql.NullString `json:"config_json"`
	CurrentStepIndex int64          `json:"current_step_index"`
	ErrorMessage     sql.NullString `json:"error_message"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
}

type WorkflowStep struct {
	ID               string         `json:"id"`
	WorkflowID       string         `json:"workflow_id"`
	StepIndex        int64          `json:"step_index"`
	StepType         string         `json:"step_type"`
	Agent            string         `json:"agent"`
	AgentSessionID   sql.NullString `json:"agent_session_id"`
	Status           string         `json:"status"`
	Title            sql.NullString `json:"title"`
	InputContextJson sql.NullString `json:"input_context_json"`
	OutputJson       sql.NullString `json:"output_json"`
	ReviewResultJson sql.NullString `json:"review_result_json"`
	RetryCount       int64          `json:"retry_count"`
	MaxRetries       int64          `json:"max_retries"`
	RequiresApproval int64          `json:"requires_approval"`
	ApprovalStatus   sql.NullString `json:"approval_status"`
	ErrorMessage     sql.NullString `json:"error_message"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	StartedAt        sql.NullInt64  `json:"started_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
}
