// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"
	"database/sql"
)

const completeWorkflow = `-- name: CompleteWorkflow :one
UPDATE workflows SET
    state = ?,
    completed_at = strftime('%s','now')
WHERE id = ?
RETURNING id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at
`

type CompleteWorkflowParams struct {
	State string `json:"state"`
	ID    string `json:"id"`
}

func (q *Queries) CompleteWorkflow(ctx context.Context, arg CompleteWorkflowParams) (Workflow, error) {
	row := q.queryRow(ctx, q.completeWorkflowStmt, completeWorkflow, arg.State, arg.ID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.State,
		&i.PlanJson,
		&i.ConfigJson,
		&i.CurrentStepIndex,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeWorkflowStep = `-- name: CompleteWorkflowStep :one
UPDATE workflow_steps SET
    status = 'completed',
    output_json = ?,
    completed_at = strftime('%s','now')
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

type CompleteWorkflowStepParams struct {
	OutputJson sql.NullString `json:"output_json"`
	ID         string         `json:"id"`
}

func (q *Queries) CompleteWorkflowStep(ctx context.Context, arg CompleteWorkflowStepParams) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.completeWorkflowStepStmt, completeWorkflowStep, arg.OutputJson, arg.ID)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    id,
    parent_session_id,
    title,
    state,
    plan_json,
    config_json,
    current_step_index,
    error_message
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at
`

type CreateWorkflowParams struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	State            string         `json:"state"`
	PlanJson         sql.NullString `json:"plan_json"`
	ConfigJson       sql.NullString `json:"config_json"`
	CurrentStepIndex int64          `json:"current_step_index"`
	ErrorMessage     sql.NullString `json:"error_message"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.queryRow(ctx, q.createWorkflowStmt, createWorkflow,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.State,
		arg.PlanJson,
		arg.ConfigJson,
		arg.CurrentStepIndex,
		arg.ErrorMessage,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.State,
		&i.PlanJson,
		&i.ConfigJson,
		&i.CurrentStepIndex,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWorkflowStep = `-- name: CreateWorkflowStep :one
INSERT INTO workflow_steps (
    id,
    workflow_id,
    step_index,
    step_type,
    agent,
    agent_session_id,
    status,
    title,
    input_context_json,
    output_json,
    review_result_json,
    retry_count,
    max_retries,
    requires_approval,
    approval_status,
    error_message
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

type CreateWorkflowStepParams struct {
	ID               string         `json:"id"`
	WorkflowID       string         `json:"workflow_id"`
	StepIndex        int64          `json:"step_index"`
	StepType         string         `json:"step_type"`
	Agent            string         `json:"agent"`
	AgentSessionID   sql.NullString `json:"agent_session_id"`
	Status           string         `json:"status"`
	Title            sql.NullString `json:"title"`
	InputContextJson sql.NullString `json:"input_context_json"`
	OutputJson       sql.NullString `json:"output_json"`
	ReviewResultJson sql.NullString `json:"review_result_json"`
	RetryCount       int64          `json:"retry_count"`
	MaxRetries       int64          `json:"max_retries"`
	RequiresApproval int64          `json:"requires_approval"`
	ApprovalStatus   sql.NullString `json:"approval_status"`
	ErrorMessage     sql.NullString `json:"error_message"`
}

func (q *Queries) CreateWorkflowStep(ctx context.Context, arg CreateWorkflowStepParams) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.createWorkflowStepStmt, createWorkflowStep,
		arg.ID,
		arg.WorkflowID,
		arg.StepIndex,
		arg.StepType,
		arg.Agent,
		arg.AgentSessionID,
		arg.Status,
		arg.Title,
		arg.InputContextJson,
		arg.OutputJson,
		arg.ReviewResultJson,
		arg.RetryCount,
		arg.MaxRetries,
		arg.RequiresApproval,
		arg.ApprovalStatus,
		arg.ErrorMessage,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows WHERE id = ?
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteWorkflowStmt, deleteWorkflow, id)
	return err
}

const deleteWorkflowSteps = `-- name: DeleteWorkflowSteps :exec
DELETE FROM workflow_steps WHERE workflow_id = ?
`

func (q *Queries) DeleteWorkflowSteps(ctx context.Context, workflowID string) error {
	_, err := q.exec(ctx, q.deleteWorkflowStepsStmt, deleteWorkflowSteps, workflowID)
	return err
}

const failWorkflowStep = `-- name: FailWorkflowStep :one
UPDATE workflow_steps SET
    status = 'failed',
    error_message = ?,
    completed_at = strftime('%s','now')
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

type FailWorkflowStepParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) FailWorkflowStep(ctx context.Context, arg FailWorkflowStepParams) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.failWorkflowStepStmt, failWorkflowStep, arg.ErrorMessage, arg.ID)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCurrentWorkflowStep = `-- name: GetCurrentWorkflowStep :one
SELECT ws.id, ws.workflow_id, ws.step_index, ws.step_type, ws.agent, ws.agent_session_id, ws.status, ws.title, ws.input_context_json, ws.output_json, ws.review_result_json, ws.retry_count, ws.max_retries, ws.requires_approval, ws.approval_status, ws.error_message, ws.created_at, ws.updated_at, ws.started_at, ws.completed_at FROM workflow_steps ws
JOIN workflows w ON ws.workflow_id = w.id
WHERE w.id = ? AND ws.step_index = w.current_step_index
LIMIT 1
`

func (q *Queries) GetCurrentWorkflowStep(ctx context.Context, id string) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.getCurrentWorkflowStepStmt, getCurrentWorkflowStep, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at FROM workflows WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id string) (Workflow, error) {
	row := q.queryRow(ctx, q.getWorkflowByIDStmt, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.State,
		&i.PlanJson,
		&i.ConfigJson,
		&i.CurrentStepIndex,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowStepByID = `-- name: GetWorkflowStepByID :one
SELECT id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at FROM workflow_steps WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkflowStepByID(ctx context.Context, id string) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.getWorkflowStepByIDStmt, getWorkflowStepByID, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const incrementStepRetry = `-- name: IncrementStepRetry :one
UPDATE workflow_steps SET
    retry_count = retry_count + 1,
    status = 'pending'
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

func (q *Queries) IncrementStepRetry(ctx context.Context, id string) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.incrementStepRetryStmt, incrementStepRetry, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listWorkflowSteps = `-- name: ListWorkflowSteps :many
SELECT id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at FROM workflow_steps 
WHERE workflow_id = ? 
ORDER BY step_index ASC
`

func (q *Queries) ListWorkflowSteps(ctx context.Context, workflowID string) ([]WorkflowStep, error) {
	rows, err := q.query(ctx, q.listWorkflowStepsStmt, listWorkflowSteps, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowStep{}
	for rows.Next() {
		var i WorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepIndex,
			&i.StepType,
			&i.Agent,
			&i.AgentSessionID,
			&i.Status,
			&i.Title,
			&i.InputContextJson,
			&i.OutputJson,
			&i.ReviewResultJson,
			&i.RetryCount,
			&i.MaxRetries,
			&i.RequiresApproval,
			&i.ApprovalStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at FROM workflows ORDER BY updated_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.query(ctx, q.listWorkflowsStmt, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.State,
			&i.PlanJson,
			&i.ConfigJson,
			&i.CurrentStepIndex,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsBySession = `-- name: ListWorkflowsBySession :many
SELECT id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at FROM workflows WHERE parent_session_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListWorkflowsBySession(ctx context.Context, parentSessionID sql.NullString) ([]Workflow, error) {
	rows, err := q.query(ctx, q.listWorkflowsBySessionStmt, listWorkflowsBySession, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.State,
			&i.PlanJson,
			&i.ConfigJson,
			&i.CurrentStepIndex,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByState = `-- name: ListWorkflowsByState :many
SELECT id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at FROM workflows WHERE state = ? ORDER BY updated_at DESC
`

func (q *Queries) ListWorkflowsByState(ctx context.Context, state string) ([]Workflow, error) {
	rows, err := q.query(ctx, q.listWorkflowsByStateStmt, listWorkflowsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.State,
			&i.PlanJson,
			&i.ConfigJson,
			&i.CurrentStepIndex,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStepAgentSession = `-- name: SetStepAgentSession :one
UPDATE workflow_steps SET
    agent_session_id = ?
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

type SetStepAgentSessionParams struct {
	AgentSessionID sql.NullString `json:"agent_session_id"`
	ID             string         `json:"id"`
}

func (q *Queries) SetStepAgentSession(ctx context.Context, arg SetStepAgentSessionParams) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.setStepAgentSessionStmt, setStepAgentSession, arg.AgentSessionID, arg.ID)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setStepApprovalStatus = `-- name: SetStepApprovalStatus :one
UPDATE workflow_steps SET
    approval_status = ?
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

type SetStepApprovalStatusParams struct {
	ApprovalStatus sql.NullString `json:"approval_status"`
	ID             string         `json:"id"`
}

func (q *Queries) SetStepApprovalStatus(ctx context.Context, arg SetStepApprovalStatusParams) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.setStepApprovalStatusStmt, setStepApprovalStatus, arg.ApprovalStatus, arg.ID)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const startWorkflowStep = `-- name: StartWorkflowStep :one
UPDATE workflow_steps SET
    status = 'running',
    started_at = strftime('%s','now')
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

func (q *Queries) StartWorkflowStep(ctx context.Context, id string) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.startWorkflowStepStmt, startWorkflowStep, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateWorkflowState = `-- name: UpdateWorkflowState :one
UPDATE workflows SET
    state = ?,
    error_message = ?
WHERE id = ?
RETURNING id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at
`

type UpdateWorkflowStateParams struct {
	State        string         `json:"state"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) (Workflow, error) {
	row := q.queryRow(ctx, q.updateWorkflowStateStmt, updateWorkflowState, arg.State, arg.ErrorMessage, arg.ID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.State,
		&i.PlanJson,
		&i.ConfigJson,
		&i.CurrentStepIndex,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateWorkflowStep = `-- name: UpdateWorkflowStep :one
UPDATE workflows SET
    current_step_index = ?
WHERE id = ?
RETURNING id, parent_session_id, title, state, plan_json, config_json, current_step_index, error_message, created_at, updated_at, completed_at
`

type UpdateWorkflowStepParams struct {
	CurrentStepIndex int64  `json:"current_step_index"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateWorkflowStep(ctx context.Context, arg UpdateWorkflowStepParams) (Workflow, error) {
	row := q.queryRow(ctx, q.updateWorkflowStepStmt, updateWorkflowStep, arg.CurrentStepIndex, arg.ID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.State,
		&i.PlanJson,
		&i.ConfigJson,
		&i.CurrentStepIndex,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateWorkflowStepStatus = `-- name: UpdateWorkflowStepStatus :one
UPDATE workflow_steps SET
    status = ?,
    error_message = ?
WHERE id = ?
RETURNING id, workflow_id, step_index, step_type, agent, agent_session_id, status, title, input_context_json, output_json, review_result_json, retry_count, max_retries, requires_approval, approval_status, error_message, created_at, updated_at, started_at, completed_at
`

type UpdateWorkflowStepStatusParams struct {
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateWorkflowStepStatus(ctx context.Context, arg UpdateWorkflowStepStatusParams) (WorkflowStep, error) {
	row := q.queryRow(ctx, q.updateWorkflowStepStatusStmt, updateWorkflowStepStatus, arg.Status, arg.ErrorMessage, arg.ID)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepIndex,
		&i.StepType,
		&i.Agent,
		&i.AgentSessionID,
		&i.Status,
		&i.Title,
		&i.InputContextJson,
		&i.OutputJson,
		&i.ReviewResultJson,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
